CREATE TABLE shipments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    tracking_number VARCHAR(255) UNIQUE NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255),
    customer_phone VARCHAR(20),
    origin_address TEXT,
    destination_address TEXT NOT NULL,
    destination_country VARCHAR(100) NOT NULL,
    package_type VARCHAR(50) NOT NULL,
    package_description TEXT,
    weight_lbs DECIMAL(10,2),
    dimensions VARCHAR(100),
    service_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    received_at TIMESTAMP,
    shipped_at TIMESTAMP,
    delivered_at TIMESTAMP,
    estimated_delivery TIMESTAMP,
    special_instructions TEXT,
    total_cost DECIMAL(10,2),
    is_paid BOOLEAN DEFAULT FALSE
);